{"name": "test_mytest1", "status": "passed", "steps": [{"name": "開始運算", "status": "broken", "statusDetails": {"message": "ValueError: value error!\n", "trace": "  File \"C:\\Users\\mon85\\git-repos\\Pytest\\test_func.py\", line 16, in func\n    raise ValueError(\"value error!\")\n"}, "start": 1664956156395, "stop": 1664956156395}], "start": 1664956156394, "stop": 1664956156399, "uuid": "db49fb45-87d9-46d0-8edf-d61bdbdc953b", "historyId": "dcabc5a2654e1ac5a3d54ab69c6657d9", "testCaseId": "3e184bcc953fa6a72e92b3fc669cbfa7", "fullName": "test_func#test_mytest1", "labels": [{"name": "suite", "value": "test_func"}, {"name": "host", "value": "LAPTOP-1LU19UGF"}, {"name": "thread", "value": "3872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_func"}]}